micronaut:
  application:
    name: eletrik
  security:
    endpoints:
      login:
        enabled: true
    authentication: bearer
    token:
      jwt:
        signatures:
          secret:
            generator:
              secret: ${JWT_GENERATOR_SIGNATURE_SECRET:ASLFKJ@#MDLOASIDP@OM#ASDLKJASLDKERMPCOASDLKJPKFD!@#ÇLKM$I!@#K}
  server:
    cors:
      enabled: true
netty:
  default:
    allocator:
      max-order: 3
password: docker
allowPublicKeyRetrieval: 'true'
user: root
dburl: jdbc:mysql://localhost:3306/mydb


