micronaut:
  application:
    name: eletrik
netty:
  default:
    allocator:
      max-order: 3
password: docker
allowPublicKeyRetrieval: 'true'
user: root
dburl: jdbc:mysql://localhost:3306/mydb
useSSL: 'false'